version: '3.8'

services:
  swarmpit:
    image: swarmpit/swarmpit:latest
    ports:
      - "8080:8080"
    environment:
      - SWARMPIT_DB=sqlite
      - SWARMPIT_SERVER=swarm
    volumes:
      - swarmpit_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

volumes:
  swarmpit_data:
