version: '3.8'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "452:452"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile  # Убедитесь, что у вас есть Caddyfile в текущем каталоге
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  caddy_data:
  caddy_config:
