version: '3.8'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "452:452"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile  # Убедитесь, что у вас есть Caddyfile в текущем каталоге
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

volumes:
  caddy_data:
  caddy_config:

